all:

	#g++ -c graphics_test.cpp
	#g++ graphics_test.o SFHelper.cpp -o run -lsfml-graphics -lsfml-window -lsfml-system
	
	g++ -c main.cpp MainMenu.cpp FirstIsland.cpp SFHelper.cpp
	g++ main.o -lsfml-graphics -lsfml-window -lsfml-system -o run
	
clean:

	rm *.o
	